// Issue Form generation (scripts/gen-issue-forms.mjs).
import { test } from "node:test";
import assert from "node:assert/strict";
import path from "node:path";
import { buildForm, buildIssueForms, buildOptions, run, toYaml, yamlScalar } from "../../scripts/gen-issue-forms.mjs";
import { bodyFields, FORMS, REQUEST_KINDS } from "../../scripts/lib/form-fields.mjs";
import { evaluateRequest } from "../../scripts/lib/issue-parse.mjs";
import { LABELS, TYPE_LABELS } from "../../site/js/lib/forms-meta.js";
import { addSecondWorld, createDataset, createDictionaries } from "../fixtures/dataset.mjs";
import { createIssue } from "../fixtures/issues.mjs";
import { memoryIo, memoryReader } from "../fixtures/memory.mjs";

const withDictionaries = () => Object.assign(createDataset(), { i18n: createDictionaries() });

test("YAML writer: double-quoted JSON strings, numbers, booleans, nesting", () => {
  assert.equal(yamlScalar('say "hi"\n'), '"say \\"hi\\"\\n"');
  assert.equal(yamlScalar(`a${String.fromCharCode(0x2028)}b`), '"a\\u2028b"');
  assert.equal(yamlScalar(0), "0");
  assert.equal(yamlScalar(false), "false");
  assert.throws(() => yamlScalar(null), TypeError);
  const yaml = toYaml({ name: "x: y", list: ["a", 1], body: [{ type: "input", attributes: { label: "L", skip: undefined } }], empty: [] });
  assert.equal(
    yaml.split("\n").slice(1).join("\n"),
    ['name: "x: y"', "list:", '  - "a"', "  - 1", "body:", '  - type: "input"', "    attributes:", '      label: "L"', "empty: []", ""].join("\n"),
  );
  assert.match(yaml, /^# Generated by scripts\/gen-issue-forms\.mjs/);
});

test("four forms plus config.yml; labels never include approved", () => {
  const files = buildIssueForms(withDictionaries());
  assert.deepEqual(
    files.map((f) => f.path),
    [
      ".github/ISSUE_TEMPLATE/1-add-point.yml",
      ".github/ISSUE_TEMPLATE/2-edit-point.yml",
      ".github/ISSUE_TEMPLATE/3-delete-point.yml",
      ".github/ISSUE_TEMPLATE/4-edit-spawn.yml",
      ".github/ISSUE_TEMPLATE/config.yml",
    ],
  );
  for (const kind of REQUEST_KINDS) {
    const form = buildForm(kind, withDictionaries());
    assert.deepEqual(form.labels, [LABELS.coordRequest, TYPE_LABELS[kind]]);
    assert.ok(!form.labels.includes(LABELS.approved));
    assert.ok(!files.find((f) => f.path.endsWith(FORMS[kind].file)).content.includes('"approved"'));
  }
});

test("options: English first, id suffix, retired tags left out, world default only for one world", () => {
  const options = buildOptions(withDictionaries());
  assert.deepEqual(options.worlds, ["Player_Club (player_club)"]);
  assert.deepEqual(options.dimensions, ["Overworld / 主世界 (overworld)", "The Nether / 地獄 (the_nether)", "The End / 終界 (the_end)"]);
  assert.deepEqual(options.tags, [
    "Base / 基地 (base)",
    "Village / 村莊 (village)",
    "Nether Fortress / 地獄要塞 (nether_fortress)",
    "Bedrock only / 基岩版限定 (bedrock_only)",
  ]);
  const worldField = (ds) => buildForm("add", ds).body.find((item) => item.id === "world");
  assert.equal(worldField(withDictionaries()).attributes.default, 0);
  assert.equal(worldField(addSecondWorld(withDictionaries())).attributes.default, undefined);
});

test("every parser heading is a generated label; tag table and Discord link are generated", () => {
  const dataset = withDictionaries();
  for (const kind of REQUEST_KINDS) {
    const yaml = toYaml(buildForm(kind, dataset));
    for (const field of bodyFields(kind)) assert.ok(yaml.includes(`label: ${JSON.stringify(field.label)}`), `${kind} ${field.id}`);
  }
  const add = toYaml(buildForm("add", dataset));
  assert.ok(add.includes("https://discord.gg/aaUQVJeCgC"));
  assert.ok(add.includes("| Bedrock only / 基岩版限定 (`bedrock_only`) | ✓ | — | — | Bedrock Edition / 基岩版 |"));
  const config = buildIssueForms(dataset).at(-1).content;
  assert.ok(config.includes("blank_issues_enabled: false"));
  assert.ok(config.includes('url: "https://discord.gg/aaUQVJeCgC"'));
  assert.ok(config.includes('url: "https://spacesquare640.github.io/Player-Club_Minecraft_Website/"'));
});

test("round trip: bodies built from the generated options pass validation", () => {
  const dataset = withDictionaries();
  const options = buildOptions(dataset);
  const cases = {
    add: { world: options.worlds[0], dimension: options.dimensions[0], name: "Base", tags: [options.tags[0], options.tags[1]], f3: "XYZ: 1.5 / 70 / -3.2" },
    edit: { target_id: "p0001", dimension: options.dimensions[0], tags: [options.tags[1]], name: "Village One" },
    delete: { target_id: "p0002" },
    spawn: { target_id: "spawn:player_club", x: "1", y: "70", z: "2" },
  };
  for (const [kind, values] of Object.entries(cases)) {
    const result = evaluateRequest({ dataset, issue: createIssue(kind, values) });
    assert.deepEqual(result.errors, [], kind);
  }
});

test("run writes the forms and --check reports drift (X22)", async () => {
  const root = path.resolve("repo-under-test");
  const reader = memoryReader(withDictionaries());
  const io = memoryIo();
  const logs = [];
  const log = (line) => logs.push(line);
  assert.equal(await run({ argv: ["--check"], root, reader, io, log }), 1);
  assert.equal(logs.filter((l) => l.includes("X22")).length, 5);
  assert.equal(io.files.size, 0);

  assert.equal(await run({ argv: [], root, reader, io, log }), 0);
  assert.equal(io.files.size, 5);
  assert.equal(await run({ argv: ["--check"], root, reader, io, log }), 0);

  const addPath = path.join(root, ".github/ISSUE_TEMPLATE/1-add-point.yml");
  io.files.set(addPath, `${io.files.get(addPath)}# hand edit\n`);
  logs.length = 0;
  assert.equal(await run({ argv: ["--check"], root, reader, io, log }), 1);
  assert.ok(logs.some((l) => l.includes("X22") && l.includes("1-add-point.yml") && l.includes("out of date")));
});

test("the committed forms match the current data", async () => {
  const logs = [];
  assert.equal(await run({ argv: ["--check"], log: (l) => logs.push(l) }), 0, logs.join("\n"));
});
